########################################
#
/myDetector/event/printModulo 100000
/gps/number 1
/gps/pos/type Point
/gps/ang/type iso
/gps/ene/type Mono

#/gps/pos/centre 0 -27.376 19.169 mm #v3

/gps/ene/mono 0 MeV

#/grdm/noVolumes
#/grdm/selectVolume Source_Disk
/gps/particle ion
/gps/ion	56  133

#/run/beamOn 88614938 #v5
#/run/beamOn 10727404 #10618947 #v4
#/run/beamOn 7214379  #v3
/run/beamOn 100000000 #v2
